<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/openscience.index.css" />
<?php
$this->headScript()->appendFile(
  $this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/index/index.index.js');
?>
<div class="viewMain">
  <h3><?php echo $this->area->getName(); ?></h3>
  
  <p><?php echo $this->area->getDescription(); ?></p>

  <b>Algorithm Performance</b>
  <br />
  <br />
  <table>
    <thead>
      <tr>
        <th>Algorithm</th>
        <th>Publications</th>
        <th>Dataset</th>
        <th>Regression Tests</th>
        <th class="last">Performance</th>
      </tr>
    </thead>
    <tbody>
<?php
  foreach ($this->algorithms as $algorithm)
    {
    echo '<tr>';
    echo '<td><a href="'.$this->webroot.'/openscience/dashboard/algorithm?id='.$algorithm->getKey().'">'.$algorithm->getName().'</a></td>';
    echo '<td><a href="'.$algorithm->getPublications().'">'.$algorithm->getName().' Publications</a></td>';
    echo '<td><a href="'.$this->webroot.'/folder/'.$algorithm->getFolderId().'">'.$algorithm->getData().'</a></td>';
    echo '<td><a href="'.$algorithm->getDashboard().'">CDash</a></td>';
    echo '<td class="last"><a href="'.$this->webroot.'/openscience/dashboard/algorithm?id='.$algorithm->getKey().'">'.$algorithm->getPerformance().'</a></td>';
    echo '</tr>';
    }
?>
    </tbody>
  </table>
</div>
<div class="viewSideBar">
  <div align="justify" class='sideElementFirst feedNotification'>
    <h1>Menu</h1>
    <ul>
      <li><a href="<?php echo $this->webroot; ?>/openscience/dashboard">Main Page</a>
  </div>
</div>