<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/openscience.index.css" />
<?php
$this->headScript()->appendFile(
  $this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/index/index.index.js');
?>
<div class="viewMain">
  <h3>Results for <?php echo $this->date; ?></h3>
  <a href="http://open.cdash.org/index.php?project=Insight&date=2012-04-24">
    Regression Test Results
  </a>
  <br />
  <br />
  <a href="http://public.kitware.com/gitweb?p=LesionSizingToolkit.git">
    Source Code
  </a>
  <br />
  <br />
<?php
  foreach ($this->results as $result)
    {
    echo '<div class="resultTile">';
    echo '  <div class="resultName">Patient: '.$result['Patient Name'].'</div>';
    echo '  <div class="resultName">Series: '.$result['Series'].'</div>';
    echo '  <div class="resultName">Timestamp: '.$result['Timestamp'].'</div>';
    echo '  <div class="resultName">Volume: '.$result['Seed 1: Volume'].'</div>';
    echo '  <a href="'.$this->webroot.'/item/'.$result['item_id'].'"><img src="'.$result['thumbnail_url'].'" width="270" /></a>';
    echo '</div>';
    }
?>
</div>
<div class="viewSideBar">
  <div align="justify" class='sideElementFirst feedNotification'>
    <h1>Menu</h1>
    <ul>
      <li><a href="<?php echo $this->webroot; ?>/openscience/dashboard">Main Page</a>
  </div>
</div>
