<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/openscience.index.css" />
<?php
$this->headScript()->appendFile(
  $this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile(
  $this->moduleWebroot . '/public/js/index/index.index.js');
?>
<div class="viewMain">
  <h3>Purpose</h3>
  <p>The Scientific method is anchored on the practice of verifying the
    reproducibility of published results. The pervasive use of computation
    in today's scientific work is such that in order to make possible to
    replicated published results, the entire set of digital resources used
    for performing the research must also be made publicly available. Is
    this demand for reproducibility that leads us to Open Science, which
    is the combination of Open Data, Open Source software, and Open Access
    publications. When all these resources are made publicly available, we
    are all empowered to repeat the experiments and verify their results
    before they become part of the accepted body of knowledge.</p>

  <p>The open science dashboard currently contains nightly, repeatable results
    over open datasets for the following anotomical areas:</p>

<?php
  foreach ($this->areas as $area)
    {
    echo '<a href="'.$this->webroot.'/openscience/dashboard/area?id='.$area->getKey().'">'.$area->getName().'</a>';
    echo '<br />';
    echo '<br />';
    }
?>
</div>
<div class="viewSideBar">
  <div align="justify" class='sideElementFirst feedNotification'>
    <h1>Menu</h1>
    <ul>
      <li><a href="<?php echo $this->webroot; ?>/openscience/dashboard">Main Page</a>
  </div>
</div>